<?php

/**
 * @file
 * Contains varbase_blog.module.
 */

/**
 * Implements hook_preprocess_HOOK() for menu.html.twig.
 */
function varbase_blog_preprocess_menu(&$variables) {
  if (isset($variables['menu_name']) && $variables['menu_name'] == 'blog-menu') {
    $variables['attributes']['class'] = [
      'nav-pills',
      'list-inline',
      'center-block',
      'justify-content-center',
    ];
  }
}
