_meta:
  version: '1.0'
  entity_type: menu_link_content
  uuid: a22d5eca-e8be-4626-a7d0-5acf9da3862d
  bundle: menu_link_content
  default_langcode: en
  depends:
    e016eb7f-7991-4ead-9248-ef9a3489e57d: node
default:
  revision_user:
    -
      target_id: 1
  revision_log_message:
    -
      value: 'Created new Custom menu link'
  enabled:
    -
      value: true
  title:
    -
      value: Blog
  menu_name:
    -
      value: main
  link:
    -
      target_uuid: e016eb7f-7991-4ead-9248-ef9a3489e57d
      title: ''
      options: {  }
  external:
    -
      value: false
  rediscover:
    -
      value: false
  weight:
    -
      value: -49
  expanded:
    -
      value: false
  revision_translation_affected:
    -
      value: true
